apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-backend.yaml
- deployment-frontend.yaml
- service-backend.yaml
- service-frontend.yaml
- ingress.yaml
- hpa.yaml
namespace: dev
images:
- name: registry.gitlab.com/somerek/music_page/backend
  newTag: 8dc4639a240e6a660ccc671af2a6ad59ae7eb4c2
- name: registry.gitlab.com/somerek/music_page/frontend
  newTag: 8dc4639a240e6a660ccc671af2a6ad59ae7eb4c2
